---
- meta: end_play
  when: (ansible_distribution != "CentOS" and ansible_distribution_major_version != "7")

- name: Install epel-release
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - epel-release

- name: Set timezone
  timezone:
    name: "{{ ntp_timezone }}"

- name: Force timesync with chrony
  shell: "chronyc -a makestep"

- name: Install additional packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - python2-cryptography
    - setools-console
    - libsemanage-python
    - policycoreutils-python

- name: Set hostname
  hostname: 
    name: "{{ ansible_hostname }}.{{ domain }}"

- name: Add my own IP address to /etc/hosts instead localhost
  replace:
    path: "/etc/hosts"
    regexp: '^127\.0\.1\.1(\s+){{ ansible_hostname }}(\s+){{ ansible_hostname }}.*'
    replace: "{{ ansible_host }} {{ ansible_hostname }}.{{ domain }} {{ ansible_hostname }}"

- name: Add node1 to /etc/hosts
  lineinfile:
    path: "/etc/hosts"
    state: present
    line: "192.168.1.11 node1.{{ domain }} {{ ansible_hostname }}"
  when: (ansible_hostname != "node1")

- name: Add node2 to /etc/hosts
  lineinfile:
    path: "/etc/hosts"
    state: present
    line: "192.168.1.12 node2.{{ domain }} {{ ansible_hostname }}"
  when: (ansible_hostname != "node2")

- name: Add node3 to /etc/hosts
  lineinfile:
    path: "/etc/hosts"
    state: present
    line: "192.168.1.13 node3.{{ domain }} {{ ansible_hostname }}"
  when: (ansible_hostname != "node3")

#- name: Enable and start FirewallD
#  systemd:
#    name: firewalld
#    state: started
#    enabled: true
...
