- name: Configuring cluster for use DLM, cLVM and create GFS2 filesystem
  shell: |
    pcs property set stonith-enabled=false
    pcs property set no-quorum-policy=freeze
    pcs resource defaults resource-stickiness=200
    pcs resource create dlm systemd:dlm op monitor interval=30s on-fail=ignore clone interleave=true ordered=true
    sleep 5
    pcs resource create clvmd ocf:heartbeat:clvm op monitor interval=30s on-fail=ignore clone interleave=true ordered=true
    sleep 5
    pcs constraint order start dlm-clone then clvmd-clone
    pvcreate /dev/mapper/mpatha
    vgcreate -Ay -cy cluster_vg /dev/mapper/mpatha
    lvcreate -L900M -n cluster_lv cluster_vg
    echo y | mkfs.gfs2 -O -j3 -p lock_dlm -t hacluster:gfs2 /dev/cluster_vg/cluster_lv
    pcs resource create clusterfs Filesystem device="/dev/cluster_vg/cluster_lv" directory="/mnt/gfs2" fstype="gfs2" "options=noatime" op monitor interval=10s on-fail=ignore clone interleave=true
    sleep 3
    pcs constraint order start clvmd-clone then clusterfs-clone
    sleep 3
    pcs constraint colocation add clusterfs-clone with clvmd-clone