---
all:
  children:
    iscsi:
      hosts:
        server:
          ansible_host: "192.168.1.10"
          ansible_private_key_file: "/home/ansible/.ssh/id_rsa"
    cluster:
      hosts:
        node1:
          ansible_host: "192.168.1.11"
          ansible_private_key_file: "/home/ansible/.ssh/id_rsa"
        node2:
          ansible_host: "192.168.1.12"
          ansible_private_key_file: "/home/ansible/.ssh/id_rsa"
        node3:
          ansible_host: "192.168.1.13"
          ansible_private_key_file: "/home/ansible/.ssh/id_rsa"
        
       #vars:
       #  virtualbox_host: "192.168.11.1"
       #  virtualbox_host_username: "mbfx"
       #  virtualbox_host_password: "strong_pass"
  vars:
    domain: "domain.local"
    ntp_timezone: "UTC"
    pcm_password: "password" #for cluster user: hacluster
    cluster_name: "hacluster"
...
