ah_token              = "FzunAjSRoqAvooqgkVoCbncX"
ah_datacenter         = "ams1"
ah_server_type        = "start-xs"
ah_image_type         = "centos-7-x64"
ssh_key_private       = "~/.ssh/id_rsa"
ansible_user          = "adminroot"
strictHostKeyChecking = "no"
pathToInventory       = "./AnsibleInventory"
